---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Update brew
        run: brew update

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Run shellcheck
        run: shellcheck *.sh backup/**.sh restore/*.sh
